title: Jiyeon's Dev Blog
description: A blog documenting my learning journey in Data Science, Machine Learning, and AI.

url: "https://jiyeonbeackuq.github.io"
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About Me
      url: /about
    - title: Projects
      url: /projects
    # - title: Contact
    #   url: /contact

social:
    github: jiyeonbeackuq
    # twitter: brianmaierjr
    # facebook: brianmaierjr
    email: j.beack@student.uq.edu.au
    linkedin: jiyeonbeack
    # youtube: RickAstleyYT
    # tumblr: i-am-a-fish

# google_analytics: "UA-58263416-1"

# disqus:
#     shortname: brianmaierjr
